version: '3'
services:
    acme-cart-nginx:
        build:
            context: ./docker/development/nginx
        volumes:
            - ./:/app
            - ./docker/development/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - acme-cart-php-fpm
        ports:
            - "8080:80"
        env_file:
            - .env
    acme-cart-php-fpm:
        build:
            context: ./docker/development/fpm
        volumes:
            - ./:/app
            - ./docker/development/fpm/config/php.ini:/usr/local/etc/php/php.ini
        environment:
            PHP_IDE_CONFIG: "serverName=AcmeCartDocker"
        env_file:
            - .env
    acme-cart-php-cli:
        build:
            context: ./docker/development/cli
        volumes:
            - ./:/app
            - ./docker/development/cli/config/php.ini:/usr/local/etc/php/php.ini
            - composer:/root/.composer/cache
        env_file:
            - .env

volumes:
    composer:
